name: Go package

on: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: Build
        run: make dist

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: gopt
          path: dist/*
