name: Go package

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 make dist
          GOOS=linux GOARCH=arm64 make dist
          GOOS=darwin GOARCH=amd64 make dist
          GOOS=darwin GOARCH=arm64 make dist

      - name: upload linux-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/gopt-linux-amd64
          asset_name: gopt-linux-amd64
          asset_content_type: application/octet-stream

      - name: upload linux-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/gopt-linux-arm64
          asset_name: gopt-linux-arm64
          asset_content_type: application/octet-stream

      - name: upload darwin-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/gopt-darwin-amd64
          asset_name: gopt-darwin-amd64
          asset_content_type: application/octet-stream

      - name: upload darwin-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/gopt-darwin-arm64
          asset_name: gopt-darwin-arm64
          asset_content_type: application/octet-stream
